### ISSUE TITLE
start_tree_search_from_current does not impact final raxml run

### ISSUE THREAD

**Issue by smirarab** [sate-dev/sate-core#16]
Final raxml run continues to use starting trees even if start_tree_search_from_current = False.

The following code in mainsate.py needs to change to check for start_tree_search_from_current

```
                post_job = rte.create_job(job.multilocus_dataset,
                                    starting_tree=job.tree,
                                    num_cpus=sate_config.num_cpus,
                                    context_str="postraxtree",
                                    tmp_dir_par=post_tree_dir,
                                    delete_temps=delete_tree_temps,
                                    sate_products=sate_products,
                                    step_num="postraxtree")
```

**Comment by joaks1** [comment]
Commit 4077ba0d68e3d4e7e55f259dab1c7a6e3989a985 modifies the behavior of the post-processing raxml search to co-opt the sate-algorithm boolean start_tree_search_from_current to determine whether to use the tree produced by the sate algorithm as a starting tree.
