### ISSUE TITLE
spaces in output dir filenames

### ISSUE THREAD

**Issue by mtholder** [sate-dev/sate-core#19]
From the GUI, selection of an output dir appears to cause sate to fail to launch (on Mac)

This has not thoroughly tested - it could be another issue (restarting and specifying an output dir without spaces seem to fix it, but it could have been a different change that fixed things).

**Comment by joaks1** [comment]
I cannot replicate this issue. The GUI appears to be able to handle spaces in the input directory name, the input file name, and the output directory name, without any problems (this is testing with version 2.2.5 on Mac OS 10.7.5). Also there is now a unit test to confirm that spaces are not a problem for the command-line version. I will close this issue, but if spaces cause problems for wxPython in other environments, this issue should be revisited.
