### ISSUE TITLE
better error message needed when tree labels do not match

### ISSUE THREAD

**Issue by mtholder** [sate-dev/sate-core#23]
A common case is when the fasta file has underscores in the names.  In Newick format requires quoting labels if you want the underscore to be preserved (rather than converted to a space).

SATe should check the names mentioned in the tree against the input sequences

**Comment by joaks1** [comment]
This issue is now resolved.  A TaxaLabelsMismatchError is now thrown if the taxon labels in the starting tree do match the sequence labels, and a summary of the mismatches is provided.
